### ISSUE TITLE
Expanded README/docs

### ISSUE THREAD

**Issue by gabrielgrant** [schell/moongraph#1]
This looks super interesting! But haven't totally wrapped my head around how the pieces fit together. Would be great to have some more documentation explaining the pieces, and some simple end-to-end examples!

**Comment by schell** [comment]
Thank you for your interest! I'll try to add some more examples for you.

**Comment by schell** [comment]
Here you go @gabrielgrant - I've added a tutorial module to the documentation (and linked it in the README). Please let me know if there are any types or concepts that could use more clarification :) 

https://docs.rs/moongraph/0.3.7/moongraph/tutorial/index.html
